name: remage-docs

channels:
  - conda-forge
  - default

dependencies:
  - python=3.12
  - breathe
  - docutils>=0.21
  - doxygen
  - exhale>=0.3.7
  - furo
  - graphviz
  - myst-parser
  - setuptools-scm
  - sphinx>=8.2
  - sphinx-copybutton
  - sphinx-togglebutton
  - sphinx-inline-tabs
  - pip:
    dependencies:
      - exhale>=0.3.7
