name: remage-docs

channels:
  - conda-forge
  - default

dependencies:
  - python=3.12
  - pip
  - breathe
  - doxygen
  - exhale
  - furo
  - graphviz
  - myst-parser
  - setuptools-scm
  - sphinx
  - sphinx-copybutton
  - sphinx-togglebutton
  - sphinx-inline-tabs
